import { GraphQLClient } from 'graphql-request';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {

    console.log(process.env.CONTENT_API);
    
    return (
        <div>
            <Head>
                <title>Max - Flores</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-cream">
                <section className='container mx-auto'>
                    <h1 className="text-8xl font-bold text-navy text-center">Max Flores</h1>
                    <p className='text-sm'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse nemo, deserunt aperiam saepe error quas molestias.</p>
                </section>
            </main>
        </div>
    );
};

export default Home;
